const EV = [
  {
    "id": 1,
    "name": "City Center Fast Charge",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "2 of 4 available",
    "location": { "latitude": 34.0522, "longitude": -118.2437 },
    "distance_km": 1.5,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station1.jpg",
    "description": "High-speed DC charging hub conveniently located in a busy downtown parking structure. \nIt is designed for quick top-ups, featuring CCS and CHAdeMO connectors. \nAccess is available 24/7, though parking fees are enforced during business hours.",
    "comment": "Fast but can be expensive during peak hours (10 AM - 4 PM)."
  },
  {
    "id": 2,
    "name": "Suburb Mall Level 2",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "6 of 8 available",
    "location": { "latitude": 34.0650, "longitude": -118.3500 },
    "distance_km": 4.2,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station2.jpg",
    "description": "Standard AC Level 2 chargers situated on the top floor of the Westside Mall parking lot, offering shaded spots. \nThis location is ideal for charging while users spend several hours shopping or dining inside the mall. \nAll spots are clearly marked with green paint and EV signage for easy identification.",
    "comment": "Great spot for charging while shopping. Free parking for 2 hours."
  },
  {
    "id": 3,
    "name": "Highway Rest Stop DC",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "1 of 6 available",
    "location": { "latitude": 34.2000, "longitude": -118.5000 },
    "distance_km": 15.8,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station3.jpg",
    "description": "An ultra-fast DC charging station strategically placed right off the main interstate highway, making it crucial for long-distance EV road trips. \nIt provides the highest available power capacity for minimum charging time, supporting both 400V and 800V architectures. \nThe station includes a small covered canopy and proximity to public restrooms and vending machines.",
    "comment": "New installation, reliable power. Expect a short wait on weekends."
  },
  {
    "id": 4,
    "name": "Downtown Parking Garage",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "4 of 5 available",
    "location": { "latitude": 34.0580, "longitude": -118.2500 },
    "distance_km": 0.8,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station4.jpg",
    "description": "DC Fast chargers located on the highly secure P1 level of a multi-story downtown parking garage. \nThis location is specifically popular among business travelers and office workers needing a mid-day energy boost. \nThe area is monitored by CCTV, providing a high level of security for vehicles while charging.",
    "comment": "Convenient for business travelers. Parking fee applies."
  },
  {
    "id": 5,
    "name": "Industrial Park Charger",
    "power_capacity_kw": 7.4,
    "status": "Inactive",
    "availability": "0 of 2 available (Maintenance)",
    "location": { "latitude": 34.1000, "longitude": -118.1500 },
    "distance_km": 8.1,
    "icon_url": "https://example.com/icons/level2_inactive.png",
    "image_url": "https://example.com/images/station5.jpg",
    "description": "Standard Level 2 chargers primarily dedicated for the use of industrial park employees and delivery vehicles during working hours. \nThe site is currently closed and marked as inactive due to necessary component replacement and scheduled electrical upgrades. \nPublic access is generally limited, but the area is typically quiet and spacious when operational.",
    "comment": "Temporarily closed for electrical upgrades. Check back next week."
  },
  {
    "id": 6,
    "name": "University Campus Lot",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "3 of 3 available",
    "location": { "latitude": 34.0200, "longitude": -118.2800 },
    "distance_km": 2.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station6.jpg",
    "description": "Public AC Level 2 chargers situated at the main entrance of the University West parking area, near the faculty buildings. \nThese chargers are specifically intended to promote EV adoption among students and university staff, offering discounted rates. \nCharging is accessible 24/7, but parking enforcement is strict during class periods.",
    "comment": "Free with a valid student/faculty ID. Pay-per-hour for public access."
  },
  {
    "id": 7,
    "name": "Residential Street Charger",
    "power_capacity_kw": 7.4,
    "status": "Active",
    "availability": "1 of 1 available",
    "location": { "latitude": 34.0800, "longitude": -118.3000 },
    "distance_km": 3.7,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station7.jpg",
    "description": "A single-unit curbside Level 2 charger recently installed by the city's infrastructure program to serve local residents. \nIt is strategically placed on a quiet residential street corner and is best suited for long-duration, overnight charging sessions. \nPayment is managed through a tap-to-pay feature on the charging post itself.",
    "comment": "Good for overnight charging. Residential area, please be quiet."
  },
  {
    "id": 8,
    "name": "Eco-Mart Supercharger",
    "power_capacity_kw": 250,
    "status": "Active",
    "availability": "5 of 10 available",
    "location": { "latitude": 34.1500, "longitude": -118.4000 },
    "distance_km": 10.1,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station8.jpg",
    "description": "A large charging depot managed by Eco-Mart, featuring ten high-powered DC units capable of 250 kW output. \nThis hub is strategically located next to the main store entrance, providing easy access to amenities while charging. \nThe facility is often busy but provides ample space and dedicated EV parking signs.",
    "comment": "Coffee shop and restrooms available inside Eco-Mart."
  },
  {
    "id": 9,
    "name": "Metro Station Charge Point",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "0 of 3 available (Occupied)",
    "location": { "latitude": 34.0400, "longitude": -118.2300 },
    "distance_km": 1.1,
    "icon_url": "https://example.com/icons/fast_occupied.png",
    "image_url": "https://example.com/images/station9.jpg",
    "description": "DC Fast chargers situated in the 'Kiss-and-Ride' area of a major Metro rail station, catering primarily to daily commuters. \nDue to its convenient location near the rail line, availability is often low during morning and evening rush hours. \nThe area is well-lit and benefits from proximity to the station security personnel.",
    "comment": "High usage area, check availability before arriving."
  },
  {
    "id": 10,
    "name": "Hotel Valet Charging",
    "power_capacity_kw": 11,
    "status": "Inactive",
    "availability": "0 of 2 available (Closed to Public)",
    "location": { "latitude": 34.0600, "longitude": -118.2700 },
    "distance_km": 2.9,
    "icon_url": "https://example.com/icons/level2_inactive.png",
    "image_url": "https://example.com/images/station10.jpg",
    "description": "Level 2 chargers located within the secure, underground parking facility of the Grand Lux Hotel, accessible only via the valet service. \nThese facilities are strictly reserved for overnight guests of the hotel and are not available for general public use. \nTheir status is marked 'Inactive' for public apps to prevent unnecessary visits.",
    "comment": "Public access is not permitted."
  },
  {
    "id": 11,
    "name": "Park & Ride Station A",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "4 of 4 available",
    "location": { "latitude": 34.1200, "longitude": -118.3800 },
    "distance_km": 6.3,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station11.jpg",
    "description": "AC Level 2 chargers installed in the commuter Park & Ride lot, designed for users who leave their cars for the full workday. \nThis site is an excellent solution for achieving a full charge while utilizing public transportation for the last leg of the commute. \nParking and charging payments are integrated via a single terminal at the lot entrance.",
    "comment": "Ideal for charging while commuting to the city center."
  },
  {
    "id": 12,
    "name": "Grocery Store Charger",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "1 of 2 available",
    "location": { "latitude": 34.0750, "longitude": -118.3200 },
    "distance_km": 3.0,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station12.jpg",
    "description": "DC Fast chargers conveniently located near the main entrance of the MegaFoods grocery store. \nThis location is perfect for shoppers needing a quick charge to cover their electricity consumption during a typical grocery run. \nUsage is often incentivized, with store loyalty card members receiving a discount or short period of free charging.",
    "comment": "Only 30 minutes of free charging with a store loyalty card."
  },
  {
    "id": 13,
    "name": "Office Tower EV Bay",
    "power_capacity_kw": 7.4,
    "status": "Active",
    "availability": "7 of 10 available",
    "location": { "latitude": 34.0450, "longitude": -118.2550 },
    "distance_km": 0.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station13.jpg",
    "description": "Level 2 charging stations situated on the ground floor of the large Apex Tower parking structure, primarily serving the building's tenants. \nPublic access is permitted only after standard business hours, generally from 6 PM to 6 AM, and on weekends. \nThe charging rate is competitive for overnight visitors to the downtown area.",
    "comment": "Public access allowed after 6 PM. Security guard on duty."
  },
  {
    "id": 14,
    "name": "Beachside Charging Spot",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "3 of 3 available",
    "location": { "latitude": 33.9900, "longitude": -118.4800 },
    "distance_km": 20.0,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station14.jpg",
    "description": "High-powered DC chargers located at the municipal beach parking lot, offering charging just steps from the sand. \nThis facility is vital for day-trippers who require a fast recharge before the drive home after a day at the coast. \nDue to the prime location, standard beach parking rates must be paid in addition to the charging fee.",
    "comment": "Excellent view while you charge. Parking rates apply."
  },
  {
    "id": 15,
    "name": "Riverside Quick Charge",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "6 of 8 available",
    "location": { "latitude": 34.0500, "longitude": -118.1800 },
    "distance_km": 6.7,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station15.jpg",
    "description": "A newly constructed ultra-fast hub on the eastern side of the city, perfectly positioned near the popular river trail and a major highway exit. \nThe 8 charging stalls are equipped with high-efficiency liquid-cooled cables to ensure peak charging performance even during hot weather. \nThere are picnic tables nearby for users to relax while they wait.",
    "comment": "Charging is very quick. Open 24/7."
  },
  {
    "id": 16,
    "name": "Old Town Slow Charge",
    "power_capacity_kw": 3.7,
    "status": "Inactive",
    "availability": "0 of 1 available (Out of Order)",
    "location": { "latitude": 34.0300, "longitude": -118.2000 },
    "distance_km": 5.2,
    "icon_url": "https://example.com/icons/slow_inactive.png",
    "image_url": "https://example.com/images/station16.jpg",
    "description": "A very slow AC charger located in a small parking area in the historic district, primarily intended for low-speed, all-day charging. \nThis single unit has been non-operational for several weeks following a reported fault with the internal circuit board. \nUsers are advised to check the status or use nearby alternatives before planning a charge here.",
    "comment": "Charger has been reported broken for 2 weeks. Do not rely on it."
  },
  {
    "id": 17,
    "name": "Museum District DC",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "2 of 4 available",
    "location": { "latitude": 34.0680, "longitude": -118.3600 },
    "distance_km": 4.5,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station17.jpg",
    "description": "DC fast charging available on the first level of the main Museum parking structure, a convenient option for visitors. \nThe facility is secure, clean, and often has spaces available as most museum visitors don't require high-speed charging. \nUse of the chargers is restricted to the museum's operating hours.",
    "comment": "Covered parking is a plus. Best used while visiting the museum."
  },
  {
    "id": 18,
    "name": "Northside EV Hub",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "4 of 5 available",
    "location": { "latitude": 34.1800, "longitude": -118.4500 },
    "distance_km": 12.2,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station18.jpg",
    "description": "A modern charging cluster featuring five high-power DC stations serving the busy Northern suburbs and adjacent commercial area. \nThis location is easily accessible directly from the main arterial road, minimizing detours for drivers. \nThe facility offers reliable power and is generally well-maintained.",
    "comment": "Always reliable and rarely full. Easy access from the freeway."
  },
  {
    "id": 19,
    "name": "Airport Long-Term Lot",
    "power_capacity_kw": 11,
    "status": "Active",
    "availability": "15 of 20 available",
    "location": { "latitude": 33.9425, "longitude": -118.4080 },
    "distance_km": 18.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station19.jpg",
    "description": "Level 2 charging available across 20 spots in the economy long-term parking lot at the international airport. \nThese spots are designed for travelers who leave their EV parked for multiple days and require a full charge upon return. \nUsers must pay the standard long-term parking fee, and a free shuttle service is provided to the main terminals.",
    "comment": "Requires a shuttle ride to the terminal. Great for long stays."
  },
  {
    "id": 20,
    "name": "Mountain View Overnight",
    "power_capacity_kw": 7.4,
    "status": "Active",
    "availability": "2 of 2 available",
    "location": { "latitude": 34.2500, "longitude": -118.5500 },
    "distance_km": 25.0,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station20.jpg",
    "description": "Quiet Level 2 chargers situated at a scenic overlook near the entrance to a major regional hiking trail and park. \nThis location is intentionally low-power, encouraging users to spend several hours enjoying the outdoor amenities while their vehicle charges slowly. \nThe site is open from dawn till dusk, with gate closures overnight.",
    "comment": "Perfect for a slow charge while hiking or picnicking."
  },
  {
    "id": 21,
    "name": "Tech Hub Fast Charger",
    "power_capacity_kw": 250,
    "status": "Active",
    "availability": "0 of 4 available (Fully Occupied)",
    "location": { "latitude": 34.0350, "longitude": -118.2650 },
    "distance_km": 1.9,
    "icon_url": "https://example.com/icons/ultra_fast_occupied.png",
    "image_url": "https://example.com/images/station21.jpg",
    "description": "High-demand DC Fast chargers serving a dense area of corporate offices and tech startups. \nThis hub is known for consistently being fully occupied during regular business hours due to its central location and high-speed capability. \nThere is often a queue, so drivers are advised to use the charging provider's app to reserve a slot if possible.",
    "comment": "Always busy during lunch hours (12 PM - 2 PM)."
  },
  {
    "id": 22,
    "name": "Community Library AC",
    "power_capacity_kw": 11,
    "status": "Active",
    "availability": "2 of 2 available",
    "location": { "latitude": 34.0700, "longitude": -118.3400 },
    "distance_km": 3.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station22.jpg",
    "description": "Level 2 chargers located in the public parking lot of the local community library, available during its operational hours. \nThis is an excellent option for users needing a medium-speed charge while reading or working inside the quiet library building. \nThe charging service itself is provided free of charge by the city, but users must adhere to a strict time limit.",
    "comment": "Free charging but limited to 4 hours."
  },
  {
    "id": 23,
    "name": "Gas Station Conversion",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "3 of 4 available",
    "location": { "latitude": 34.1050, "longitude": -118.4100 },
    "distance_km": 7.8,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station23.jpg",
    "description": "A site that was successfully converted from a traditional petrol station into a modern EV charging hub, maintaining a familiar layout. \nIt features four high-speed DC charging points and the original convenience store is still operational, offering good amenities. \nThe open forecourt allows for easy maneuvering and access for larger vehicles.",
    "comment": "Easy in and out access. Good store amenities."
  },
  {
    "id": 24,
    "name": "Hotel Overnight B",
    "power_capacity_kw": 7.4,
    "status": "Inactive",
    "availability": "0 of 5 available (Private Access)",
    "location": { "latitude": 34.0550, "longitude": -118.2850 },
    "distance_km": 2.1,
    "icon_url": "https://example.com/icons/level2_inactive.png",
    "image_url": "https://example.com/images/station24.jpg",
    "description": "Five Level 2 chargers located in the secured basement parking of the Lakeside Hotel. \nThese spots are exclusively reserved and provisioned only for registered hotel guests with an active room key and are inaccessible to the general public. \nThe 'Inactive' status on the public network reflects this private-use policy.",
    "comment": "Strictly no public charging. Guard will check room key."
  },
  {
    "id": 25,
    "name": "Retail Park Charger",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "1 of 1 available",
    "location": { "latitude": 34.1600, "longitude": -118.3000 },
    "distance_km": 9.9,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station25.jpg",
    "description": "A single DC Fast charger serving a large, busy retail and restaurant park area. \nDue to its singularity and proximity to popular stores, it experiences high demand, and there is a high risk of being occupied or blocked by unauthorized vehicles. \nIt provides a necessary quick charge option for shoppers.",
    "comment": "Can get blocked by non-EVs often. Call site management if needed."
  },
  {
    "id": 26,
    "name": "Central Park South",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "5 of 6 available",
    "location": { "latitude": 34.0400, "longitude": -118.2700 },
    "distance_km": 1.7,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station26.jpg",
    "description": "City-operated Level 2 charging spots located directly on the street adjacent to the Southern entrance of Central Park. \nThese curb-side units utilize smart-city infrastructure and are managed by a local parking authority application. \nIt's a convenient location for visitors spending a full day at the park or nearby attractions.",
    "comment": "Best for charging early mornings before the street fills up."
  },
  {
    "id": 27,
    "name": "Marina View Fast Lane",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "4 of 4 available",
    "location": { "latitude": 33.9600, "longitude": -118.4500 },
    "distance_km": 22.0,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station27.jpg",
    "description": "A dedicated charging station offering ultra-fast DC power with a spectacular, unobstructed view of the marina and ocean. \nThis location features four state-of-the-art charging units capable of delivering peak power to compatible vehicles. \nIt is a destination charger popular with tourists, offering nearby cafes and restrooms.",
    "comment": "Parking can be tight with large vehicles. Beautiful location."
  },
  {
    "id": 28,
    "name": "Art Gallery Parking",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "0 of 2 available (Occupied)",
    "location": { "latitude": 34.0720, "longitude": -118.2900 },
    "distance_km": 3.3,
    "icon_url": "https://example.com/icons/fast_occupied.png",
    "image_url": "https://example.com/images/station28.jpg",
    "description": "DC Fast chargers available in the secure, underground parking facility of the city's main Art Gallery and cultural center. \nThis option is excellent for a quick boost while visitors are inside the gallery or enjoying the surrounding cultural district. \nAccess and charging are only permitted during the gallery's operating hours, which typically run from 9 AM to 6 PM.",
    "comment": "Only accessible during gallery opening hours (9 AM - 6 PM)."
  },
  {
    "id": 29,
    "name": "Residential Cul-de-sac",
    "power_capacity_kw": 7.4,
    "status": "Inactive",
    "availability": "0 of 1 available (Permit Only)",
    "location": { "latitude": 34.1300, "longitude": -118.3300 },
    "distance_km": 7.0,
    "icon_url": "https://example.com/icons/level2_inactive.png",
    "image_url": "https://example.com/images/station29.jpg",
    "description": "A standard AC Level 2 charger unit installed on a local residential cul-de-sac street corner. \nThis charger is strictly designated for residents who have purchased a specific local EV charging permit from the community association. \nIt is marked 'Inactive' for the public network as unauthorized use may result in towing or penalties.",
    "comment": "Do not attempt to charge here without a local permit. You may be towed."
  },
  {
    "id": 30,
    "name": "Factory Outlet DC",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "1 of 6 available",
    "location": { "latitude": 34.1900, "longitude": -118.2000 },
    "distance_km": 11.5,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station30.jpg",
    "description": "A cluster of six DC Fast chargers strategically located near the food court entrance of a major factory outlet mall. \nThis location is specifically designed to provide a fast charge during the typical 60-90 minute visit of shoppers. \nAmenities are excellent, with numerous food and beverage options available nearby.",
    "comment": "Excellent amenities for spending time during a charge."
  },
  {
    "id": 31,
    "name": "City Hall Public Bay",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "3 of 4 available",
    "location": { "latitude": 34.0530, "longitude": -118.2400 },
    "distance_km": 1.0,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station31.jpg",
    "description": "Public AC Level 2 charging spaces designated right in front of the City Hall building, ideal for quick administrative visits. \nThese chargers are regulated by the city and enforce a strict 4-hour time limit during business hours to ensure high turnover. \nPayment is managed through the city's standard parking meter system or mobile app.",
    "comment": "Limited to 4 hours on weekdays due to high demand."
  },
  {
    "id": 32,
    "name": "South Bay DC Station",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "2 of 5 available",
    "location": { "latitude": 33.8500, "longitude": -118.3800 },
    "distance_km": 28.9,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station32.jpg",
    "description": "A primary high-speed charging hub serving the South Bay and the end of the coastal route. \nThe five stalls offer ultra-fast 350kW power, making it a critical point for long-distance drivers entering or leaving the metropolitan area. \nThe facility is solar-powered and features a small, shaded lounge area for waiting customers.",
    "comment": "Always reliable for a quick charge before hitting the beach."
  },
  {
    "id": 33,
    "name": "Midtown Parking Lot",
    "power_capacity_kw": 50,
    "status": "Inactive",
    "availability": "0 of 3 available (Power Failure)",
    "location": { "latitude": 34.0850, "longitude": -118.3550 },
    "distance_km": 5.0,
    "icon_url": "https://example.com/icons/fast_inactive.png",
    "image_url": "https://example.com/images/station33.jpg",
    "description": "DC Fast chargers located in a small, privately-owned midtown surface parking lot. \nThe entire facility is currently experiencing a critical power failure in the charging equipment, rendering all three units inactive. \nMaintenance is pending, but an estimated time for repair (ETA) has not yet been provided by the operator.",
    "comment": "Out of service due to recent grid issues. No ETA for repair."
  },
  {
    "id": 34,
    "name": "Eastside Community Center",
    "power_capacity_kw": 11,
    "status": "Active",
    "availability": "1 of 2 available",
    "location": { "latitude": 34.0200, "longitude": -118.1500 },
    "distance_km": 9.4,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station34.jpg",
    "description": "Level 2 chargers conveniently situated next to the public swimming pool and gymnasium at the Eastside Community Center. \nThis is an ideal place to plug in for the moderate-speed charging required while using the recreational facilities for a few hours. \nThe chargers are available to the public during center operating hours.",
    "comment": "Easy parking. Can charge while using the center facilities."
  },
  {
    "id": 35,
    "name": "West LA Quick Stop",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "3 of 6 available",
    "location": { "latitude": 34.0600, "longitude": -118.4400 },
    "distance_km": 14.8,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station35.jpg",
    "description": "A popular DC Fast hub featuring six high-power stalls located in a high-traffic retail area of West LA near several major intersections. \nDespite its popularity, the high number of units often ensures a short waiting time for a charger. \nThe area provides quick access to several fast-food and coffee establishments.",
    "comment": "Reliable but often sees high turnover. Expect a short wait."
  },
  {
    "id": 36,
    "name": "Canyon Drive Level 2",
    "power_capacity_kw": 7.4,
    "status": "Active",
    "availability": "1 of 1 available",
    "location": { "latitude": 34.1500, "longitude": -118.6000 },
    "distance_km": 28.0,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station36.jpg",
    "description": "An isolated, single Level 2 charger unit located at the designated public parking area near the end of a scenic canyon road. \nThis spot is primarily utilized by hikers and park visitors who plan to leave their vehicle for an extended period. \nIt is the only public charging option in this remote area.",
    "comment": "Very peaceful, but slow. Only suitable for long visits to the area."
  },
  {
    "id": 37,
    "name": "Financial District DC",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "0 of 4 available (Fully Occupied)",
    "location": { "latitude": 34.0500, "longitude": -118.2600 },
    "distance_km": 0.3,
    "icon_url": "https://example.com/icons/fast_occupied.png",
    "image_url": "https://example.com/images/station37.jpg",
    "description": "Four DC Fast chargers located in the basement parking of a high-rise building in the absolute center of the Financial District. \nThis station is currently the closest to the city center and experiences the highest utilization rate during business hours (9 AM - 5 PM). \nDrivers should be prepared for potential queuing due to the extremely high demand for charging.",
    "comment": "Highest traffic charger in the city. Best used very late at night."
  },
  {
    "id": 38,
    "name": "Metro North Station",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "8 of 10 available",
    "location": { "latitude": 34.1000, "longitude": -118.3000 },
    "distance_km": 4.1,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station38.jpg",
    "description": "A very large installation of ten Level 2 chargers situated in the main parking facility of a major Metro interchange, catering to a large commuter base. \nThe high number of stalls generally ensures good availability, making it a reliable choice for a full day's charging while using public transport. \nIt is an exceptionally well-lit and monitored facility.",
    "comment": "Plenty of spaces available. Safe and well-lit."
  },
  {
    "id": 39,
    "name": "Small Business Charger",
    "power_capacity_kw": 7.4,
    "status": "Inactive",
    "availability": "0 of 1 available (Restricted)",
    "location": { "latitude": 34.1800, "longitude": -118.3500 },
    "distance_km": 10.5,
    "icon_url": "https://example.com/icons/level2_inactive.png",
    "image_url": "https://example.com/images/station39.jpg",
    "description": "A Level 2 unit that is privately owned and operated by a small business specifically for their own fleet vehicles and employees. \nThere are physical barriers or a coded gate system that prevent unauthorized public access to the charging spot. \nIt is listed as inactive on the public map to clearly indicate that it is not available for general use.",
    "comment": "Public charging is not allowed. Barrier is usually down."
  },
  {
    "id": 40,
    "name": "Valley View Ultra Fast",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "5 of 6 available",
    "location": { "latitude": 34.2000, "longitude": -118.5200 },
    "distance_km": 17.5,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station40.jpg",
    "description": "The newest ultra-fast DC hub in the greater San Fernando Valley region, featuring next-generation 350kW charging technology. \nThis station is strategically positioned to attract drivers traveling along the main Valley thoroughfare. \nIt includes a dedicated, climate-controlled rest area with seating and Wi-Fi for drivers.",
    "comment": "Very fast speeds achieved. Dedicated rest area nearby."
  },
  {
    "id": 41,
    "name": "Main Street Public Lot",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "2 of 2 available",
    "location": { "latitude": 34.0560, "longitude": -118.2350 },
    "distance_km": 1.3,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station41.jpg",
    "description": "Two DC Fast chargers located in a highly visible area of a city-operated public parking lot on Main Street. \nThis location is crucial for quick stops while conducting business in the primary downtown commercial zone. \nCharging is generally reliable, and parking payment is separate from the charging session.",
    "comment": "Pay for parking via the mobile app."
  },
  {
    "id": 42,
    "name": "Westside Corporate Park",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "9 of 12 available",
    "location": { "latitude": 34.0400, "longitude": -118.4200 },
    "distance_km": 12.0,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station42.jpg",
    "description": "A substantial array of twelve Level 2 chargers situated in the visitor parking area of a large, multi-company corporate campus. \nWhile primarily for visitors, the facility is publicly accessible and is often used by local residents in the evenings and on weekends when availability is highest. \nCharging access is typically free during non-business hours.",
    "comment": "Best availability on weekends. Free after 5 PM."
  },
  {
    "id": 43,
    "name": "Riverfront Walk Charger",
    "power_capacity_kw": 7.4,
    "status": "Active",
    "availability": "1 of 1 available",
    "location": { "latitude": 34.0800, "longitude": -118.1800 },
    "distance_km": 7.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station43.jpg",
    "description": "A single Level 2 charging post located right off the main pedestrian and bike path along the riverfront walkway. \nIts low power capacity is suited for individuals spending a significant amount of time (e.g., several hours) exercising or relaxing in the recreational area. \nThis unit is powered by an adjacent solar array, providing a green charging solution.",
    "comment": "Beautiful, quiet location for a longer charge."
  },
  {
    "id": 44,
    "name": "Shopping Center DC Hub",
    "power_capacity_kw": 150,
    "status": "Active",
    "availability": "2 of 3 available",
    "location": { "latitude": 34.1200, "longitude": -118.4800 },
    "distance_km": 15.5,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station44.jpg",
    "description": "Three high-speed DC Fast charging spots located in the dedicated EV section of the West Valley Shopping Center's main lot. \nThe area is highly visible and conveniently situated near the cinema and large retail anchor stores. \nThis spot is essential for fast charging while running major errands or watching a movie.",
    "comment": "Chargers are well marked and easy to find near the cinema."
  },
  {
    "id": 45,
    "name": "Suburban Street Light",
    "power_capacity_kw": 3.7,
    "status": "Inactive",
    "availability": "0 of 1 available (Damaged)",
    "location": { "latitude": 34.1600, "longitude": -118.3900 },
    "distance_km": 11.0,
    "icon_url": "https://example.com/icons/slow_inactive.png",
    "image_url": "https://example.com/images/station45.jpg",
    "description": "A very slow charging unit integrated directly into a standard public street light pole in a quiet suburban neighborhood. \nThis infrastructure was part of a pilot program and has recently become inactive after being physically damaged by a passing vehicle. \nIt is awaiting replacement parts, and repair is expected within the next two months.",
    "comment": "Damaged by a vehicle last month. Waiting for repair parts."
  },
  {
    "id": 46,
    "name": "Convention Center Garage",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "5 of 8 available",
    "location": { "latitude": 34.0450, "longitude": -118.2680 },
    "distance_km": 0.9,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station46.jpg",
    "description": "Eight DC Fast chargers situated on the P3 level of the city's massive Convention Center parking garage. \nAvailability fluctuates wildly depending on whether a major conference or trade show is currently running at the center. \nDue to the security of the facility, this is a trusted spot, although garage entry/exit can be slow during peak traffic.",
    "comment": "Accessibility can be difficult during large events."
  },
  {
    "id": 47,
    "name": "Hospital Visitor Parking",
    "power_capacity_kw": 22,
    "status": "Active",
    "availability": "3 of 5 available",
    "location": { "latitude": 34.0800, "longitude": -118.2200 },
    "distance_km": 4.0,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station47.jpg",
    "description": "Five Level 2 chargers located in the designated visitor parking area of the central city hospital campus. \nThese are intended to serve individuals visiting patients or staff working on short shifts, providing a crucial service to the community. \nUsers should note that all standard hospital parking fees must be paid in addition to the charging cost.",
    "comment": "Only use if visiting the hospital. Hospital parking rates apply."
  },
  {
    "id": 48,
    "name": "New Development DC Hub",
    "power_capacity_kw": 350,
    "status": "Active",
    "availability": "6 of 6 available",
    "location": { "latitude": 34.2200, "longitude": -118.4000 },
    "distance_km": 14.2,
    "icon_url": "https://example.com/icons/ultra_fast_active.png",
    "image_url": "https://example.com/images/station48.jpg",
    "description": "A brand new, fully-staffed, dedicated charging facility built as part of a major commercial development project. \nIt boasts six ultra-fast 350kW charging stalls and consistently reports 100% operational availability due to proactive maintenance. \nThis location is known for providing one of the most reliable and highest-quality charging experiences in the entire region.",
    "comment": "One of the best charging experiences in the region. Always available."
  },

  {
    "id": 49,
    "name": "Local Diner Charger",
    "power_capacity_kw": 50,
    "status": "Active",
    "availability": "1 of 1 available",
    "location": { "latitude": 34.1500, "longitude": -118.3200 },
    "distance_km": 8.5,
    "icon_url": "https://example.com/icons/fast_active.png",
    "image_url": "https://example.com/images/station49.jpg",
    "description": "A single DC Fast charger conveniently placed in the parking lot of 'Sam's Classic Diner,' offering a retro-themed waiting experience. \nThis unit is a fantastic option for travelers who need a charge and also desire a full meal during their charging session. \nDrivers are encouraged to check with the diner staff for any special deals or payment integrations.",
    "comment": "Great place to eat a meal while charging. Check with the diner for payment methods."
  },
  {
    "id": 50,
    "name": "Ferry Terminal EV Point",
    "power_capacity_kw": 11,
    "status": "Active",
    "availability": "2 of 3 available",
    "location": { "latitude": 33.9500, "longitude": -118.4200 },
    "distance_km": 24.5,
    "icon_url": "https://example.com/icons/level2_active.png",
    "image_url": "https://example.com/images/station50.jpg",
    "description": "Three Level 2 chargers located within the main commuter parking area of the regional ferry terminal. \nThese are intended to service individuals who leave their vehicles for the duration of a ferry crossing or a full workday commute to an island destination. \nGiven the 8-hour round trip on the ferry, the moderate speed of the chargers is perfectly adequate.",
    "comment": "Perfect for a long charge while taking the ferry."
  }
]

// module.exports = { data: EV };
export default EV;